services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ../../../../Certs/RedisDO.crt:/usr/local/etc/redis/RedisDO.crt
