version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=:8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=test
      - DB_NAME=test
      - SECRET_KEY=JWTTOKENBACKENDDEVELOPMENT
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"